### ISSUE TITLE
does not make on Kubuntu 12.04 - multiple errors

### ISSUE THREAD

**Issue by tomdavidson** [patrickjennings/FlickrMS#1]
Installed FUSE 2.8.6, Flickcurl-1.21-5, and build-essentials. My system is Kubuntu  3.2.0-26-generic #41-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux.

1st make error:
/bin/sh: 1: pkg-config: not found
flickrms.c:4:18: fatal error: fuse.h: No such file or directory
compilation terminated.
make[1]: **\* [flickrms.o] Error 1

installed pkg-config 0.26. So pkg-config is a dependency?

2nd make error:
Package fuse was not found in the pkg-config search path.  
Perhaps you should add the directory containing `fuse.pc'  
to the PKG_CONFIG_PATH environment variable  
No package 'fuse' found  
flickrms.c:4:18: fatal error: fuse.h: No such file or directory  
compilation terminated.  
make[1]: **\* [flickrms.o] Error 1

fuse is installed. tried updating the environment variable with "echo "export PKG_CONFIG_PATH=\$PKG_CONFIG_PATH:/usr/""`find -name "fuse.pc" \ | head -n 1 | xargs dirname`" >> ~/.bash_profile"

no go.  installed libfuse-dev.

3rd make error:
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package flickcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing`flickcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'flickcurl' found
cache.c:10:23: fatal error: flickcurl.h: No such file or directory
compilation terminated.

glib-2.0 is installed.

tried installing libflickcurl-dev, still get the glib stuff:
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
cache.c:14:18: fatal error: glib.h: No such file or directory
compilation terminated.
make[1]: **\* [cache.o] Error 1

installed libglib2.0-dev and am left with:
make[1]: Entering directory `/home/xxxxx/bin/FlickrMS/src'
gcc -Wall -W -Werror -Wextra -g`pkg-config --cflags --libs glib-2.0` `pkg-config --cflags --libs flickcurl` -c cache.c
cache.c: In function ‘flickr_init’:
cache.c:84:2: error: implicit declaration of function ‘flickcurl_config_read_ini’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[1]: **\* [cache.o] Error 1
make[1]: Leaving directory `/home/tom/bin/FlickrMS/src'
make: **\* [all] Error 2

Im not sure how to proceeded but would love to use FlickrMS. Can you give me some direction?

**Comment by patrickjennings** [comment]
I've updated the README with the additional dependencies. The wiki has info on how to install using Ubuntu. Let me know if your still having problems installing and I can help you out.
