### ISSUE TITLE
Size of retrieved images

### ISSUE THREAD

**Issue by lboullo0** [patrickjennings/FlickrMS#5]
All images are downloaded in medium size instead of its original size. Is there a way to configure this?

**Comment by patrickjennings** [comment]
I've updated master so the default image it will retrieve will be the original photo. Pull the latest code and give it a shot.

It will be a little slower on initial load, especially if you use a file browser with previewing of files enabled. You can change the image size by editing GET_PHOTO_SIZE in cache.c. Also, Flickrms re-downloads the photos every 20 minutes by default to sync any changes done through the Flickr website. You may alter PHOTO_TIMEOUT in flickrms.c to change this time period to a longer duration, if you wish.

Eventually, I will add program arguments where you can specify all of these parameters on filesystem mount.

Let me know how it works out!

**Comment by lboullo0** [comment]
Thank you again.
After I execute:
`flickrms /media/Flickr/`
all images in that directory have the same size as before the patch (ie, all images have 1 kb).
However I discover that in:
~/.flickrms/
All images have the original size
