### ISSUE TITLE
DSO missing from command line

### ISSUE THREAD

**Issue by klevis-a** [patrickjennings/FlickrMS#8]
On Ubuntu 16.04 when running make the following error results:

/usr/bin/ld: wget.o: undefined reference to symbol 'round@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line

This can be fixed by changing the makefile as follows:

OBJS:=flickrms.o cache.o wget.o conf.o -lm

**Comment by patrickjennings** [comment]
I confirmed the issue in 16.04. -lm was defined in LDFLAGS but the order of the library linking was incorrect. It's been fixed in master. Thank you for making me aware of this!

**Comment by klevis-a** [comment]
No problem, thank you for putting together such a useful tool!
